jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Schritt 1: Repository klonen 2
      - name: Checkout repository
        uses: actions/checkout@v3

      # Schritt 2: Installieren der Abhängigkeiten
      - name: Install Dependencies
        run: |
          yarn install

      # Schritt 3: Anwendung starten oder neu starten (PM2)
      - name: Start or Restart Application
        run: |
          pm2 describe OEE_solution > /dev/null || pm2 start server.js --name "OEE_solution"
          pm2 restart OEE_solution --update-env
