name: Deploy Node.js Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          yarn install

      - name: Start or Restart Application in Production
        run: |
          pm2 start ecosystem.config.js --env production || pm2 restart OEE_solution --env production
